# application name
spring:
  application:
    name: hr-payroll


# port and name
server:
  port: 8101

# eureka client configuration
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
    # register-with-eureka: true
    # fetch-registry: true
