# default port
server:
  port: 8001

spring:
  application:
    name: hr-worker

# h2 database connection data
  datasource:
    url: jdbc:h2:mem:testdb
    username: sa
    password:
    driver-class-name: org.h2.Driver

  # h2 database web client configuration
  h2:
    console:
      enabled: true
      path: /h2-console
      settings:
        trace: false
        web-allow-others: true

  # configuration to show SQL in console
  jpa:
    open-in-view: false
    show-sql: false
    properties:
      hibernate:
        format_sql: true
