# server name
spring:
  application:
    name: hr-config-server
  cloud:
    config:
      server:
        git:
          default-label: main
          uri: https://github.com/RicardoLopes1/ms-course-configs
          #username: ${GITHUB_USERNAME}
          #password: ${GITHUB_PASSWORD}

# server port
server:
  port: 8888
