# server name
spring:
  application:
    name: hr-config-server
  cloud:
    config:
      server:
        git:
          default-label: main
          uri: https://github.com/RicardoLopes1/ms-course-configs

# server port
server:
  port: 8888
