# project name
spring:
  application:
    name: hr-eureka-server

# server port
server:
  port: 8761

# eureka server
eureka:
  client:
    register-with-eureka: false
    fetch-registry: false
  # server:
  #   enable-self-preservation: false
