# default port
server:
  #port: 8011
  port: ${PORT:0}

# eureka client configuration
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
    # register-with-eureka: false
    # fetch-registry: false
  instance:
    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}

spring:
  application:
    name: hr-user

# h2 database connection data
  datasource:
    url: jdbc:h2:mem:testdb
    username: sa
    password:
    driver-class-name: org.h2.Driver

  # h2 database web client configuration
  h2:
    console:
      enabled: true
      path: /h2-console
      settings:
        trace: false
        web-allow-others: true

  # configuration to show SQL in console
  jpa:
    open-in-view: false
    show-sql: false
    properties:
      hibernate:
        format_sql: true
