# default port
server:
  #port: 8011
  port: ${PORT:0}

# eureka client configuration
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
    # register-with-eureka: false
    # fetch-registry: false
  instance:
    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}

spring:
  application:
    name: hr-user
