# application name
spring:
  application:
    name: hr-api-gateway-zuul

# application port
server:
  port: 8765

# eureka client configuration
eureka:
  client:
    service-url:
      defaultZone: http://hr-eureka-server:8761/eureka
    # register-with-eureka: false
    # fetch-registry: false

# Hystrix configuration (timeout)
hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 60000

ribbon:
  ConnectTimeout: 10000
  ReadTimeout: 20000

# zuul routes
zuul:
  routes:
    worker:
      path: /hr-worker/**
      serviceId: hr-worker
    payroll:
      path: /hr-payroll/**
      serviceId: hr-payroll
    user:
      path: /hr-user/**
      serviceId: hr-user
    oauth:
      path: /hr-oauth/**
      serviceId: hr-oauth
      sensitive-headers: Cookie,Set-Cookie
